version: '2'
services:
  flask:
    build: .
    ports:
        - 5000:5000
    #restart: on_failure

  python:
    image: python
    command: ['/bin/bash']

networks:
  default:
    external:
      name: net
